builders:
  preferences_builder:
    import: "package:libleaf/builder.dart"
    builder_factories: ["preferencesBuilder"]
    build_extensions: {"^assets/preferences.json": ["lib/generated/preferences.dart"]}
    auto_apply: root_package
    build_to: source