name: liblymph
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.example.com
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build: ^2.3.0

  code_builder: ^4.1.0

  collection: ^1.16.0
  cryptography: ^2.0.5

  dart_style: ^2.2.3
  drift: ^1.4.0

  json_annotation: ^4.5.0

  path: ^1.8.1

  recase: ^4.0.0

  uuid: ^3.0.6

  webcrypto:
    git: https://github.com/gargakshit/webcrypto.dart

dev_dependencies:
  build_runner: ^2.1.7

  dependency_validator: ^3.2.0
  drift_dev: ^1.4.0

  json_serializable: ^6.1.4

  lint: ^1.8.2
  
  test: ^1.16.0
