name: libleaf
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.example.com
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^4.1.0
  
  build: ^2.3.0

  code_builder: ^4.1.0

  collection: ^1.16.0
  drift: ^1.4.0

  glob: ^2.1.0
  json_annotation: ^4.5.0

  path: ^1.8.1

  recase: ^4.0.0

  source_gen: ^1.2.2

  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.7

  drift_dev: ^1.4.0

  json_serializable: ^6.1.4

  lint: ^1.8.2
  
  test: ^1.16.0
